name: mlgeo
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.3.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bleach=4.1.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - cffi=1.14.6
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.4
  - curl=7.78.0
  - cycler=0.10.0
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.1
  - fiona=1.8.20
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=3.3.1
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geos=3.9.1
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - hdf4=4.2.15
  - hdf5=1.12.1
  - icu=68.1
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.1
  - ipython=7.27.0
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter_client=7.0.2
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - kealib=1.4.14
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.78.0
  - libdeflate=1.7
  - libffi=3.3
  - libgdal=3.3.1
  - libglib=2.68.4
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=13.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - mapclassify=2.4.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - networkx=2.3
  - notebook=6.4.3
  - numpy=1.21.2
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.2
  - pandoc=2.14.2
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=8.3.2
  - pip=21.2.4
  - pixman=0.40.0
  - poppler=21.03.0
  - poppler-data=0.4.11
  - postgresql=13.3
  - proj=8.0.1
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - pycparser=2.20
  - pygments=2.10.0
  - pyparsing=2.4.7
  - pyproj=3.2.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.1
  - pywin32=301
  - pywinpty=1.1.4
  - pyzmq=22.2.1
  - qt=5.12.9
  - rasterio=1.2.8
  - rtree=0.9.7
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - shapely=1.7.1
  - six=1.16.0
  - snuggs=1.4.7
  - sqlite=3.36.0
  - tbb=2021.3.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tiledb=2.3.4
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.0
  - tzdata=2021a
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - winpty=0.4.3
  - xerces-c=3.2.3
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0

